backend:
  name: github
  repo: rockvinny/portfolio
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "sobre"
    label: "Página Sobre"
    folder: "content/sobre"
    create: true
    slug: "index"
    fields:
      - { label: "Mini Bio", name: "bio", widget: "text" }
      - label: "Itens da Página Sobre"
        name: "itens"
        widget: "list"
        fields:
          - { label: "Subtítulo", name: "subtitulo", widget: "string" }
          - { label: "Conteúdo", name: "conteudo", widget: "text" }
